apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: agri-food-api-5xx-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
  - name: agri-food-api.rules
    rules:
    - alert: AgriFoodApiHigh5xxErrorRate
      expr: |
        (
          sum(rate(http_requests_total{job="agri-food-api",status=~"5.."}[1m]))
          /
          sum(rate(http_requests_total{job="agri-food-api"}[1m]))
        ) * 100 > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "🚨 Agri Food API 5xx error rate yuqori"
        description: "5xx error rate 5% dan oshdi (hozir: {{ $value }}%)"
